### PR TITLE
FA-210 Fixed style for datetime

### PR DESCRIPTION
**Pull request by rahatarmanahmed**
https://formio.atlassian.net/browse/FA-210

Thanks @Gillardo for releasing breaking changes as a patch update.

### CODE REVIEW

**Comment by travist** [comment]
:+1:

**Comment by Gillardo** [comment]
What is this?

**Comment by randallknutson** [comment]
Sorry about that. One of our developers venting that a patch update broke our build. According to Semantic Versioning a breaking change should be more than a patch update.

**Comment by rahatarmanahmed** [comment]
Specifically [v1.1.1](https://github.com/Gillardo/bootstrap-ui-datetime-picker/commit/5560e74ea62d8edf478ccd1d23da847ec0c01136#diff-f9cdd05060b2d532a3a90d2fff0cc2e5L1), where the datetime-picker class changed to datetime-picker-dropdown.

**Comment by Gillardo** [comment]
Lol. No worries.

Had a lot to do on that project lately and didn't think many people were
using it or would be effected by such a change.

What is this project ngFormio? Something angular I am guessing?

**Comment by Gillardo** [comment]
And really wasn't a "breaking" change as only allowed style changes. But
will remember for next time

**Pull request merged**
