### PR TITLE
Allow any number of columns with width, offset, push and pull settings

### PR DESCRIPTION
**Pull request by douglaselee**
Would be nice to be able to have more than two columns and be able to control their Bootstrap width, offset, push and pull styles.  See related pull request in ngFormBuilder.

### CODE REVIEW

**Comment by travist** [comment]
This is awesome @douglaselee and is a much requested feature. Thank you so much!  We will review and try to pull into the next versions.  You rock man!

**Comment by douglaselee** [comment]
Happy to help Travis and, as always, thanks to you and your team for FormIO which really rocks!

**Comment by travist** [comment]
It seems that this will break reverse compatibility for any forms created before this change is made. Can you make some modifications to allow for forms without the "columns" setting to work like they did before this change is made?

**Comment by douglaselee** [comment]
Hi Travis,

Lines 16 to 30 added to src/components/columns.js in the initial commit are designed to add the new column settings to older forms.  I tested this before creating the PR and just retested but am not seeing any problem in the renderer or builder when opening older forms.  Can you tell me what is the symptom of the incompatibility and how you are reproducing it?

**Comment by travist** [comment]
Oh I see how that works now. I was confused since I saw the columns setting and was thinking that would not be present for older forms. Looks good, thanks!

**Comment by douglaselee** [comment]
Happy to help Travis!

**Pull request merged**
