### PR TITLE
Take initial values for resource component search from URL

### PR DESCRIPTION
**Pull request by douglaselee**
For example, suppose my form contains a Resource component whose API key is 'application' and whose Search Fields are 'data.state, _id'.
Then I can specify the initial value for the data.state search with a URL like .../form/59259f9614746b2a8819866c/?application.data.state=CA
Or I can specify a specific resource by id with a URL like .../form/59259f9614746b2a8819866c/?application._id=59259f0914746b2a8819866a
This is useful for apps implementing multi-form workflows.
Also if there is an initial search which finds a single resource go ahead and select it.
Also fix problem with new search results being appended to old ones.

### CODE REVIEW

**Comment by travist** [comment]
I am not completely following the need for this pull request, but considering you have committed a lot of quality contributions, I am willing to take this as long as you can verify that this is reverse compatible.

**Comment by douglaselee** [comment]
Thanks Travis.  Regarding reverse compatibility the commit does not make or depend on any schema changes to forms, components, submissions...

**Comment by travist** [comment]
Thanks @douglaselee. You have really been a great asset to this project.

**Comment by douglaselee** [comment]
Thanks @travist I'm happy to hear that.  Formio has been a lifesaver for me so you're very welcome!

**Pull request merged**
