### PR TITLE
Fix various issues with the file upload component

### PR DESCRIPTION
**Pull request by douglaselee**
With display file as image option set upload 3 files.  Delete the second.  Correct file will be deleted from array but images will appear as if the last one had been deleted.

Also send delete requests to server for URL storage when deleting.  This should probably be done for Dropbox and S3 too but I'm not in a position code or test that now.

### CODE REVIEW

**Comment by travist** [comment]
We will probably need to get this tested on all the providers before we can pull this into place.

**Comment by douglaselee** [comment]
Don't think it could hurt Dropbox or S3.  Just won't help them since, as coded, sending of the delete request is conditional on storage type.  Should probably be moved down to formio.js level to make it work for all providers.

The part about image ordering and other bulletproofing is independent of provider.

**Comment by travist** [comment]
Thanks!

**Comment by douglaselee** [comment]
Happy to help!

**Pull request merged**
